services:
  api-tester-ia:
    build: .
    container_name: api-tester-ia
    ports:
      - "3000:3000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db-alt
    volumes:
      - .:/usr/src/app
    command: npm start

  db-alt:
    image: postgres:15
    container_name: api-tester-db-alt
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5433:5432" # Expondo 5433 local -> 5432 no container
    volumes:
      - pgdata-alt:/var/lib/postgresql/data

volumes:
  pgdata-alt:
